[exclude]
regex = ["https://www.linkedin.com/.*"]

[checks]
exclude_paths = [
  "README.md",
  "_pages/404.md",
  "_pages/blog.md",
  "_posts/2018-12-22-distill.md",
  "_includes/experiences.html"
]

[verbosity]
level = "verbose"

[progress]
disable = true
